### PR TITLE
ADD: boxplot mark properties

### PR DESCRIPTION
**Pull request by pratapvardhan**

### CODE REVIEW

**Comment by jakevdp** [comment]
I don't think we want to do this, because boxplot behaves differently than other plot types. For example:
```python
>>> pd.Series(np.random.randn(100)).plot.box(alpha=0.5)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-28-d0e37c0840b3> in <module>
      1 pd.Series(np.random.randn(100))#pd.DataFrame({'x': [1, 2, 3, 4, 5], 'y':[2, 1, 4, 2, 3], 'a':list('AABBA')})
      2 pd.set_option('plotting.backend', 'matplotlib')
----> 3 pd.Series(np.random.randn(100)).plot.box(alpha=0.5)

~/anaconda/lib/python3.6/site-packages/pandas/plotting/_core.py in box(self, by, **kwargs)
   1076             >>> ax = df.plot.box()
   1077         """
-> 1078         return self(kind="box", by=by, **kwargs)
   1079 
   1080     def hist(self, by=None, bins=10, **kwargs):

~/anaconda/lib/python3.6/site-packages/pandas/plotting/_core.py in __call__(self, *args, **kwargs)
    792                     data.columns = label_name
    793 
--> 794         return plot_backend.plot(data, kind=kind, **kwargs)
    795 
    796     def line(self, x=None, y=None, **kwargs):

~/anaconda/lib/python3.6/site-packages/pandas/plotting/_matplotlib/__init__.py in plot(data, kind, **kwargs)
     60             kwargs["ax"] = getattr(ax, "left_ax", ax)
     61     plot_obj = PLOT_CLASSES[kind](data, **kwargs)
---> 62     plot_obj.generate()
     63     plot_obj.draw()
     64     return plot_obj.result

~/anaconda/lib/python3.6/site-packages/pandas/plotting/_matplotlib/core.py in generate(self)
    279         self._compute_plot_data()
    280         self._setup_subplots()
--> 281         self._make_plot()
    282         self._add_table()
    283         self._make_legend()

~/anaconda/lib/python3.6/site-packages/pandas/plotting/_matplotlib/boxplot.py in _make_plot(self)
    136 
    137             ret, bp = self._plot(
--> 138                 ax, y, column_num=0, return_type=self.return_type, **kwds
    139             )
    140             self.maybe_color_bp(bp)

~/anaconda/lib/python3.6/site-packages/pandas/plotting/_matplotlib/boxplot.py in _plot(cls, ax, y, column_num, return_type, **kwds)
     52         else:
     53             y = remove_na_arraylike(y)
---> 54         bp = ax.boxplot(y, **kwds)
     55 
     56         if return_type == "dict":

~/anaconda/lib/python3.6/site-packages/matplotlib/__init__.py in inner(ax, *args, **kwargs)
   1853                         "the Matplotlib list!)" % (label_namer, func.__name__),
   1854                         RuntimeWarning, stacklevel=2)
-> 1855             return func(ax, *args, **kwargs)
   1856 
   1857         inner.__doc__ = _add_data_doc(inner.__doc__,

TypeError: boxplot() got an unexpected keyword argument 'alpha'
```

**Comment by pratapvardhan** [comment]
I'm conflicted if altair_pandas too should fail when matplotlib backend fails. Intuitively, I'd normally want to style boxplot color. I'll let you decide and close this. :-)

**Comment by jakevdp** [comment]
``plot.box()`` has other means of controlling mark color, which we should support: https://pandas.pydata.org/pandas-docs/stable/user_guide/visualization.html#box-plots

I think we should avoid diverging from the behavior of the matplotlib backend whenever possible.

**Comment by pratapvardhan** [comment]
Closing in agreement.

**Pull request closed without merging**
